### PR TITLE
Fix unit test

### PR DESCRIPTION
**Pull request by isaacplmann**

### CODE REVIEW

**Comment by isaacplmann** [comment]
Fixes #74 .  I pulled the `attachTo` logic out of the directive and into it's service.  Also fixed a little bug in the directive.

**Comment by vlio20** [comment]
while the travis does its job, can you please elaborate on the bug you fixed?

**Comment by isaacplmann** [comment]
Actually, I both introduced and fixed the bug in the same PR, so it never existed in your repo.  The directive was overriding the config object with a default one, so any changes (like setting `appendTo` were being ignored).

**Comment by vlio20** [comment]
ok. thanks!

**Pull request merged**
