### PR TITLE
Added calls for isMonthDisabledCallback

### PR DESCRIPTION
**Pull request by thierrydussau**

### CODE REVIEW

**Comment by vlio20** [comment]
@thierrydussau is this PR still relevant? I want to have it for the next version of the lib

**Comment by thierrydussau** [comment]
Unless there was a major rework for next version, yes I think that call was missing and should be added.
Thanks for your work on this by the way!

**Comment by vlio20** [comment]
@thierrydussau, for me to accept this PR (and sorry for the late replay) I will need to have an issue, documentation and e2e tests.

Also, note that PR should be made to the next branch.

**Comment by thierrydussau** [comment]
Makes sense, I will close this as I unfortunately I won’t have the time to work on this, and given our requirement we had to build on our thing.

**Pull request closed without merging**
