### PR TITLE
B 269

### PR DESCRIPTION
**Pull request by vlio20**

### CODE REVIEW

**Comment by dgroh** [comment]
Any plans for a release date?

**Comment by vlio20** [comment]
can't tell... have few more bugs and not lot of time unfortunately

**Comment by dgroh** [comment]
fair enough, just asking...would appreciate if I could help with PRs

**Comment by dgroh** [comment]
no not yet, we went through `dev` and are now in `test`, waiting for `qa` and then `prod`. this might take a few weeks...even so unfortunately only AD authenticated users are able to navigate to the website.

**Comment by vlio20** [comment]
Could share a screen shot?

**Comment by dgroh** [comment]
Sure...

image

**Comment by vlio20** [comment]
awesome! thanks!

**Pull request merged**
