### PR TITLE
Added year-picker calendar, with a demonstration on the Demo page

### PR DESCRIPTION
**Pull request by joakimgk**
I've modified the month-picker into a year-picker, in its own, separate directory.
I hope I've configured the new calendar mode correctly in the overall module setup. I have only created the `dp-year-calendar` directive, and I have _not_ modified `date-picker.component.ts` or `date-picker.service.ts`, which I have a feeling I should have. However, the year picker works on the demo page, so I think this is a good start!

### CODE REVIEW

**Comment by vlio20** [comment]
Seems like your code breaks Travis. Also please make sure you are on the next branch and submitting the pull request on this branch and not master.

**Comment by vlio20** [comment]
@joakimgk, please put your questions here

**Comment by joakimgk** [comment]
I've fixed the lint errors. Could you please point me in the right direction?

**Comment by vlio20** [comment]
Why did you close it?

**Comment by joakimgk** [comment]
Hit the wrong button. Also, won't I open a new pull request (on the "next"
branch) anyway?

20. okt. 2017 06.07 skrev "Vlad Ioffe" <notifications@github.com>:

**Comment by vlio20** [comment]
you should, but you don't need to close the issue.

**Pull request closed without merging**
