### PR TITLE
Fixed an issue with current location button not aligned in the middle.

### PR DESCRIPTION
**Pull request by KevinJannis**

### CODE REVIEW

**Comment by KevinJannis** [comment]
Image attached.

screen shot 2017-10-30 at 10 27 42

**Comment by vlio20** [comment]
In what browser the issue happens?

**Comment by KevinJannis** [comment]
IE11/Edge
This could be a conflict with other css, but I think it is a good idea to add this as a default anyway.

**Comment by vlio20** [comment]
how does it looks after the change ? can you post a photo pls?

**Comment by KevinJannis** [comment]
As requested, the datepicker after the change:
screen shot 2017-10-31 at 08 39 28

**Comment by vlio20** [comment]
Thanks for the PR, could please create a new one on the next branch and open an issue for your fix. I will be more than happy to merge your PR.

**Comment by KevinJannis** [comment]
See: https://github.com/vlio20/angular-datepicker/pull/273

**Pull request closed without merging**
