### PR TITLE
Manual keyboard input issue

### PR DESCRIPTION
**Pull request by CosteaMihai**

### CODE REVIEW

**Comment by CosteaMihai** [comment]
Fixes #540

**Review by vlio20 — CHANGES_REQUESTED** [review]
please remove the changes in package-lock.json

**Comment by CosteaMihai** [comment]
@vlio20 modifications requested done

**Comment by vlio20** [comment]
Another request, can this fix be tested (unit test or e2e)?

**Comment by vlio20** [comment]
@CosteaMihai ?

**Comment by CosteaMihai** [comment]
@vlio20 Can you be more specific? To run the test you wrote in order to see if everything is fine?

**Comment by vlio20** [comment]
@CosteaMihai just to add an e2e test. You can seen many examples under the e2e directory. Let me know you if you need extra help.

**Comment by vlio20** [comment]
@CosteaMihai, long time passed... are you planning to add test to your PR?

**Pull request closed without merging**
