### PR TITLE
Feature/angular 17

### PR DESCRIPTION
**Pull request by henrikgrubbe**
Issue trying to solve
https://github.com/vlio20/angular-datepicker/issues/638

Hope this is satisfactory. Angular 17 support would be nice. 
Thank you for a very useful library!

### CODE REVIEW

**Comment by vlio20** [comment]
@henrikgrubbe please note that the build is failing

**Comment by henrikgrubbe** [comment]
The error doesn't seem to be related to Angular 17. Rather with the way tests are set up. I have no experience with Protractor, so I'm a bit at a loss here. I'm afraid the issue is related to Protractor's end of life status..

**Comment by vlio20** [comment]
I will try to make it work in the next couple of days

**Comment by pvds** [comment]
Hi @vlio20 did you get a chance to look at the protractor issue?

**Comment by pvds** [comment]
@vlio20 maybe use the latest stable chrome version? 

`sudo apt-get install google-chrome-stable`

**Comment by pvds** [comment]
@vlio20 `114.0.5735.343` seems to be the [last released 114 version](https://chromium.googlesource.com/chromium/src/+/refs/tags/114.0.5735.343), maybe that one is available?

**Comment by vlio20** [comment]
I am working on moving to playwrite. It will take a day or two but this is
something that have to be done.

**Comment by vlio20** [comment]
thanks @henrikgrubbe I have merged the PR and release a new 17.0.0 version that is now available on NPM.

Thanks again!

**Comment by henrikgrubbe** [comment]
Awesome, great work. Thank you very much!

**Pull request merged**
